blog:
  sqlite:
    url: database.db
# tomcat
server:
  tomcat:
    uri_encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8089
  servlet:
    context-path: /springboot-sqlite
# spring
spring:
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 100MB
        msx-request-size: 100MB
        enabled: true

# logger config
logging:
  level:
    com.vnightray.springsqlitetest.*: debug